Changed state to update properly, added empty views array on initialization of a new media type
SolsticeAR/solsticeAR-admin-client pull request #11
Opened 2019-09-18 15:21 UTC by jmourell

2019-09-18 16:01 UTC, wilandrade requested changes

2019-09-18 16:01 UTC, wilandrade commented on src/reducers/index.js
> +        campaigns: data.campaigns.slice(0)
Why is this better than destructuring?

2019-09-18 16:01 UTC, wilandrade commented on src/reducers/index.js
> +      // const newState = { ...state };
please delete comments

2019-09-18 16:01 UTC, wilandrade commented
Please remember to add descriptions to all pull requests.

Good work here!

2019-09-18 21:42 UTC, jmourell commented on src/reducers/index.js
> +        campaigns: data.campaigns.slice(0)
It really depends on what you'd like to do I can keep it as an object of objects or change it to an array of objects.  I can destructure it as an array too. Either way is alright.

2019-09-19 01:15 UTC, wilandrade commented on src/reducers/index.js
> +        campaigns: data.campaigns.slice(0)
Ahh, I see it now. It was set up as an object...

2019-09-19 01:18 UTC, wilandrade approved these changes
LGTM

2019-09-19 02:00 UTC, merged